
name: expense_tracker_flutter
description: Simple factory expense tracker
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: any
  firebase_core: any

flutter:
  uses-material-design: true
